// <auto-generated />
using System;
using Interview.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Interview.Api.Data.Migrations
{
    [DbContext(typeof(AnalyticsDbContext))]
    partial class AnalyticsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Interview.Api.Data.AiChatTurn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AssistantExcerpt")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorSummary")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EstimatedCostUsd")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT");

                    b.Property<int>("HttpStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int?>("OutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PromptTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserMessage")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("VisitSessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("VisitorKey")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("VisitSessionId");

                    b.ToTable("AiChatTurns");
                });

            modelBuilder.Entity("Interview.Api.Data.PageView", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("EnteredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LeftAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VisitSessionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EnteredAtUtc");

                    b.HasIndex("VisitSessionId");

                    b.ToTable("PageViews");
                });

            modelBuilder.Entity("Interview.Api.Data.VisitSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AcceptLanguage")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("EndedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("LandingPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Referrer")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferrerHost")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ScreenHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ScreenWidth")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeZone")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ViewportHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ViewportWidth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VisitorKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StartedAtUtc");

                    b.HasIndex("VisitorKey");

                    b.ToTable("VisitSessions");
                });

            modelBuilder.Entity("Interview.Api.Data.AiChatTurn", b =>
                {
                    b.HasOne("Interview.Api.Data.VisitSession", "VisitSession")
                        .WithMany("AiChatTurns")
                        .HasForeignKey("VisitSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("VisitSession");
                });

            modelBuilder.Entity("Interview.Api.Data.PageView", b =>
                {
                    b.HasOne("Interview.Api.Data.VisitSession", "VisitSession")
                        .WithMany("PageViews")
                        .HasForeignKey("VisitSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VisitSession");
                });

            modelBuilder.Entity("Interview.Api.Data.VisitSession", b =>
                {
                    b.Navigation("AiChatTurns");

                    b.Navigation("PageViews");
                });
#pragma warning restore 612, 618
        }
    }
}
